name: Run GHA
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout spreadsheet-cfml Repository
      uses: actions/checkout@v4
      with:
        repository: cfsimplicity/spreadsheet-cfml
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install the ortus security key
      run: curl -fsSl https://downloads.ortussolutions.com/debs/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/ortussolutions.gpg > /dev/null

    - name: Add the commandbox source
      run: echo "deb [signed-by=/usr/share/keyrings/ortussolutions.gpg] https://downloads.ortussolutions.com/debs/noarch /" | sudo tee /etc/apt/sources.list.d/commandbox.list

    - name: Update apt and install commandbox
      run: sudo apt-get update && sudo apt-get install apt-transport-https commandbox

    - name: Install dependencies
      run: box install

    - name: Start a server
      run: box server start cfengine=lucee@5 port=8080

    - name: Run TestBox Tests
      run: box testbox run runner="http://localhost:8080/test/index.cfm"
